version: "3.5"

services:
  api:
    build: .
    hostname: api
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=projectmanagement
    ports:
      - "5432:5432"
    volumes:
      - ./Database/Scheme.sql:/docker-entrypoint-initdb.d/Scheme.sql
      - ./Database/Data.sql:/docker-entrypoint-initdb.d/Data.sql
